name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  logging: ^1.3.0
  smooth_page_indicator: ^1.2.1
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  webview_flutter: ^4.10.0
  flutter_secure_storage: ^9.2.2
  speech_to_text: ^7.0.0
  flutter_otp_text_field: ^1.1.0+2
  flutter_launcher_icons: ^0.14.3
  country_flags: ^3.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/.config
    - assets/images/
    - assets/images/icons/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
