// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/integrations/auth_repository_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:app/data/services/google_auth.dart' as _i4;
import 'package:app/data/services/http.dart' as _i5;
import 'package:app/data/services/secure_storage.dart' as _i7;
import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthentication_1 extends _i1.SmartFake
    implements _i3.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleAuthImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthImpl extends _i1.Mock implements _i4.GoogleAuthImpl {
  MockGoogleAuthImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i3.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i2.Future<_i3.GoogleSignInAccount?>.value(),
          )
          as _i2.Future<_i3.GoogleSignInAccount?>);

  @override
  _i2.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [HttpServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpServiceImpl extends _i1.Mock implements _i5.HttpServiceImpl {
  MockHttpServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> post<T>(String? path, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path, body]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#post, [path, body]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#post, [path, body])),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> postMultipart<T>(
    String? path,
    Map<String, dynamic>? fields,
    Map<String, List<int>>? files,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postMultipart, [path, fields, files]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#postMultipart, [path, fields, files]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#postMultipart, [path, fields, files]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> get<T>(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#get, [path]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#get, [path])),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<void> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> put<T>(String? path, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path, body]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#put, [path, body]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#put, [path, body])),
          )
          as _i2.Future<T>);
}

/// A class which mocks [SecureStorageImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageImpl extends _i1.Mock implements _i7.SecureStorageImpl {
  MockSecureStorageImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i3.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.Future<_i3.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i2.Future<_i3.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_1(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i2.Future<_i3.GoogleSignInAuthentication>);

  @override
  _i2.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i2.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i2.Future<Map<String, String>>);

  @override
  _i2.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i3.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}
