name: Flutter CI (Android & Web)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Enable Web
        run: flutter config --enable-web

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Format code
        run: dart format --set-exit-if-changed --output=none .

      - name: Create assets/.config with secrets
        run: |
          mkdir -p assets
          echo "API_URL = ${{ secrets.CONFIG_API_URL }}" > assets/.config
          echo "GOOGLE_CLIENT_ID=${{ secrets.CONFIG_GOOGLE_CLIENT_ID }}" >> assets/.config

      - name: Run all tests
        run: flutter test
